name: Spotless
on:
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-24.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Check if Spotless has been applied
    - name: Check Spotless formatting
      if: github.ref
      run: ./gradlew spotlessCheck
