name: Spotless
on:
  pull_request:
    branches: [ main ]
jobs:
  spotless:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-24.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Apply Spotless formatting if needed
    - name: Apply Spotless formatting
      if: github.ref
      run: ./gradlew spotlessApply
    # Check if there are any changes after applying Spotless formatting
    - name: Check for changes
      if: github.ref
      id: git_diff
      run: |
        if git diff --exit-code; then
          echo "No changes to commit"
          echo "::set-output name=changes::false"
        else
          echo "Changes detected"
          echo "::set-output name=changes::true"
        fi
    # Commit and push changes if there are any
    - name: Commit and push changes
      if: steps.git_diff.outputs.changes == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git commit -am "Apply Spotless formatting"
        git push origin HEAD:${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}